# -*- coding: utf-8 -*-
"""Task2_Oasis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTnTAqXFOY1F6Wkkr1Qm1rDvOocA4nfe

Oasis Taks_2  **Unemployment Analysis with Python**
"""

#importing the libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

#importing the dataset from google drive
df = pd.read_csv('/content/drive/MyDrive/Unemployment_Rate_upto_11_2020.csv')
df.head()

#Checking for the null values in the dataset
df.isnull().sum()

df.info()

#checking for the corelation of all the features form the dataset
df.corr()

plt.figure(figsize=(10, 5))
correlations = df.corr()
sns.heatmap(correlations, cmap="RdYlBu_r", annot=True)
plt.show()

#Data Vitualizations
#taking a look at the estimated number of employees according to different regions of India

plt.title("Indian Unemployment")
sns.histplot(x="Estimated Employed", hue="Region", data=df)
plt.show()

#unemployment rate according to different regions of India
plt.figure(figsize=(12, 10))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate", hue="Region", data=df)
plt.show()